show, update, delete
DiptoSarkar182/quiz-app-api pull request #2
Opened 2024-11-20 11:13 UTC by DiptoSarkar182

Added show, update and delete for category, sub category and sub category quiz.

2024-11-20 13:05 UTC, JakariaJishan commented on app/controllers/categories_controller.rb
> +    end
I think it's fine to query here directly for show action

2024-11-20 13:07 UTC, JakariaJishan commented on app/controllers/categories_controller.rb
> +  end
I don't think that separating methods at model level for normal crud action

2024-11-20 13:08 UTC, JakariaJishan commented on app/controllers/sub_categories_controller.rb
> +  end
same goes here

2024-11-20 13:12 UTC, JakariaJishan commented on app/controllers/sub_category_quizzes_controller.rb
> +  end
Do you need to strong params? I think it's better to merge extra params with strong params when needed

2024-11-20 13:12 UTC, JakariaJishan commented on app/controllers/sub_category_quizzes_controller.rb
>  end
add extra empty line at the bottom

2024-11-20 13:14 UTC, JakariaJishan commented on app/models/category.rb
> +    end
You are nesting two levels deep if else condition.
`return { status::not_found, message: "Category not found!" } unless category.present?`
this is a good approach I think

2024-11-20 13:16 UTC, JakariaJishan commented on app/models/sub_category.rb
> +  end
same goes here

2024-11-20 13:17 UTC, JakariaJishan commented on app/models/sub_category_quiz.rb
> +    end
same here

2024-11-20 13:19 UTC, JakariaJishan requested changes
Please check all the comments

2024-11-20 13:44 UTC, DiptoSarkar182 commented on app/controllers/sub_category_quizzes_controller.rb
> +  end
Added extra params.

2024-11-20 13:45 UTC, DiptoSarkar182 commented on app/controllers/sub_category_quizzes_controller.rb
>  end
Added extra line at the bottom.

2024-11-20 13:59 UTC, DiptoSarkar182 commented on app/models/category.rb
> +    end
Added the suggested code.

2024-11-20 14:03 UTC, DiptoSarkar182 commented on app/models/sub_category.rb
> +  end
Added the suggested code.

2024-11-20 14:08 UTC, DiptoSarkar182 commented on app/models/sub_category_quiz.rb
> +    end
Added the suggested code.

2024-11-21 08:26 UTC, JakariaJishan approved these changes
Approved. It's time to merge. 
<img src="https://media4.giphy.com/media/paYMkqI9PFkVSKcSuN/giphy.gif"/>

2024-11-21 08:47 UTC, merged